# Generated by Django 5.2.4 on 2025-09-05 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "scenario_type",
                    models.CharField(
                        choices=[
                            ("urban", "Urban Delivery"),
                            ("highway", "Highway Transport"),
                            ("mixed", "Mixed Use"),
                            ("long_haul", "Long Haul"),
                            ("regional", "Regional"),
                            ("custom", "Custom Scenario"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("conventional", "Conventional ICE"),
                            ("hybrid", "Hybrid Electric"),
                            ("plugin_hybrid", "Plug-in Hybrid"),
                            ("battery_electric", "Battery Electric"),
                            ("fuel_cell", "Fuel Cell Electric"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fuel_type", models.CharField(max_length=50)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "maintenance_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "lifespan",
                    models.IntegerField(
                        blank=True, help_text="Lifespan in years", null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TCOAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_cost_of_ownership",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="t3co_app.scenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Vehicle"),
                            ("comparison", "Vehicle Comparison"),
                            ("fleet", "Fleet Analysis"),
                            ("demo", "Demo Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("vehicle_file", models.CharField(blank=True, max_length=500)),
                ("scenario_file", models.CharField(blank=True, max_length=500)),
                ("results", models.JSONField(default=dict)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scenarios",
                    models.ManyToManyField(blank=True, to="t3co_app.scenario"),
                ),
                ("vehicles", models.ManyToManyField(blank=True, to="t3co_app.vehicle")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
